### ISSUE TITLE
Waiting for backend.. if this message persists, there is a bug.

### ISSUE THREAD

**Issue by TheChaosToast** [DrWarpMan/sinusbot-scripts#2] opened 2021-02-16 07:52 UTC
Hi

I'm currently trying out your Script OS Groups. The bot has the necessary rights, but I get the following error message:

Waiting for backend .. if this message persists, there is a bug.

What am I doing wrong? I completely restarted the bot and also changed the bot's permissions. The bot is authorized to add server groups.

Thanks for an answer

**Comment by DrWarpMan** [comment] 2021-02-17 12:48
Hello, could you please send me your configuration?

**Comment by TheChaosToast** [comment] 2021-02-17 15:57
Hi,

Thank you for your prompt reply. I assume that you mean the configuration of the web interface, I added it as an attachment. The server groups are entered according to the operating system. When I create a user with a new identity and connect it to the test server, I get the error message.

I hope that this is enough for you as info :) - oh well, I haven't found a direct download anywhere and have copied the content of the file into an empty file.

But I think if there were formatting errors the script wouldn't work at all?!
Thanks for your help :)

![os_groups_sinusbot](https://user-images.githubusercontent.com/36563709/108230401-08d63100-7141-11eb-9080-745206bd93bc.png)

The Error message:

`
2021-02-17T17:08:50+01:00 Waiting for backend.. if this message persists, there is a bug.
2021-02-17T17:08:39+01:00 Waiting for backend.. if this message persists, there is a bug.
2021-02-17T17:08:36+01:00 Waiting for backend.. if this message persists, there is a bug.
2021-02-17T17:08:19+01:00 Waiting for backend.. if this message persists, there is a bug.
2021-02-17T17:08:07+01:00 Waiting for backend.. if this message persists, there is a bug.
2021-02-17T17:06:59+01:00 Waiting for backend.. if this message persists, there is a bug.
2021-02-17T17:06:50+01:00 Waiting for backend.. if this message persists, there is a bug.
2021-02-17T17:06:30+01:00 Waiting for backend.. if this message persists, there is a bug.
2021-02-17T17:06:27+01:00 Waiting for backend.. if this message persists, there is a bug.
2021-02-17T17:06:05+01:00 Waiting for backend.. if this message persists, there is a bug.
2021-02-17T17:06:03+01:00 Waiting for backend.. if this message persists, there is a bug.
2021-02-17T17:05:48+01:00 [ staff-list:741:20] Staff-List > The script has loaded successfully!
2021-02-17T17:05:47+01:00 unloaded instance
2021-02-17T17:05:45+01:00 [ anti-solitary:179:10] Started Anti-Solitary-Clients (1.2.3) by >> @TwentyFour <<
2021-02-17T17:05:45+01:00 script staff-list loaded
2021-02-17T17:05:45+01:00 script osGroups loaded
2021-02-17T17:05:45+01:00 [Script] "OS Groups" [Version] "1.0.2" [Author] "DrWarpMan <drwarpman@gmail.com>"
2021-02-17T17:05:45+01:00 script anti-solitary loaded
2021-02-17T17:05:45+01:00 script countOnlineUsers loaded
2021-02-17T17:05:45+01:00 script OKlib loaded
2021-02-17T17:05:44+01:00 script command loaded
`

**Comment by DrWarpMan** [comment] 2021-02-17 19:33
The problem is that I implemented a function that should eliminate one tiny annoying Sinusbot thingy, which is:

> _When the bot joins the server, it thinks that every client on the server that Sinusbot sees, has just connected,
which means if Sinusbot joins on a 100 people server, it will instantly fire clientMove event - 100 times!
This might not be a problem for a small community server, but there are people with hundreds of clients
and this would cause a lag for them._

For now, if you won't have problems, you can just use this version of the script: https://pastebin.com/raw/4U34cUhY
Don't worry though, I am already solving this with flyth (the creator & owner of Sinusbot).

Thanks for writing me btw!

**Comment by TheChaosToast** [comment] 2021-02-19 05:25
I'll sit down on the weekend and try it, I'll get back to you in any case :)

**Comment by TheChaosToast** [comment] 2021-02-20 11:03
Hi,

it seems to work with the pastebin script. Unfortunately I currently have too few users on the server to tell you exactly whether it works. currently 3 people are online and there it goes. Anyway, the logs look promising so far.

I will get back to you again if there are any problems.

Thank you

**Comment by DrWarpMan** [comment] 2021-02-20 11:54
Hello,

thanks for the feedback, I will leave this issue open to remind me that I should figure out a fix for this thing.
Whenever you have anything to add to this problem, you are free to reply.

Thanks as well!

**Comment by TheChaosToast** [comment] 2021-02-20 15:30
heyho my friend,

the pastebin script works quite well so far - 40 users are currently online. seems to be because of that :)

**Comment by TheChaosToast** [comment] 2021-02-22 10:46
Hi,

I discovered a new bug:

`
2021-02-22T11:41:16+01:00 WARNING: Group with ID: 47 NOT found!
2021-02-22T11:41:15+01:00 Recognized OS: "Windows" (UID: yVKUPEjWxxxxxxxxxxxxxxx=)
2021-02-22T11:41:15+01:00 LXST CXNTURY just connected, checking OS..
2021-02-22T11:41:10+01:00 WARNING: Group with ID: 47 NOT found!
2021-02-22T11:41:10+01:00 Recognized OS: "Windows" (UID: f42XRDyEAKZFqxxxxxxxxxxxxxxxx=)
2021-02-22T11:41:10+01:00 DieBanane just connected, checking OS..
`

The group definitely exists. And still the error message comes?

**Comment by DrWarpMan** [comment] 2021-02-22 10:51
Can you send me your TS3 server address please?

**Comment by TheChaosToast** [comment] 2021-02-22 11:12
ts.mgc-le.de

**Comment by TheChaosToast** [comment] 2021-02-22 11:35
The script is already working and working as far as I can see it. But this error message comes up (which I can probably ignore)

**Comment by DrWarpMan** [comment] 2021-02-22 11:41
Well I don't see any group with ID 47 on your server though.
Only 48, which is Android.

**Comment by TheChaosToast** [comment] 2021-02-22 11:55
Heyho my friend,

then I probably came across the field while scrolling and accidentally pressed a counter: /

I've just changed it and logged in with my smartphone. It was really like that - thank you very much for your help :)

I deleted the server address again :)

Thank you for your help

**Closed as completed** 2023-12-23 22:34 UTC
Labels: bug
